### ISSUE TITLE
No module named scipy

### ISSUE THREAD

**Issue by neuro-bro** [ArtemKirsanov/BlenderSpike#2]
Hey, just tried to install the addon and I get the error:

```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scipy'
```

Tried to install manually from `cmd` at _C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\python\bin_ but I get the following when trying to import scipy in blenders console (to check if it installed, which it did).

```
>>>import sys
>>>sys.path.append('C:\\Users\\Me\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\python\\lib\\site-packages')

>>>import scipy
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\python\lib\site-packages\scipy\__init__.py", line 170, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\python\lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\python\lib\site-packages\scipy\_lib\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\Desktop\3D\BUILDS\daily\blender-4.1.0-alpha+daily.515d25fbedff\4.1\python\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.1\python\lib\site-packages\scipy\__init__.py", line 175, in <module>
    raise ImportError(msg) from e
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.
```
### Setup
Win 10
Blender 4.1 (installed via Blender Launcher - Daily Alpha tab)
Using your latest release

Thanks for any help!

**Comment by itsonlyjames** [comment]
I faced this same issue and fixed in this PR: https://github.com/ArtemKirsanov/BlenderSpike/pull/3

Easy fix to copy, but should be merged in soon 👍
